<?php
/**
 * Header Template
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>
<!DOCTYPE html>
	<!--[if lt IE 7]>
	<html class="ie ie6 lte9 lte8 lte7" <?php language_attributes(); ?>>
	<![endif]-->
	<!--[if IE 7]>
	<html class="ie ie7 lte9 lte8 lte7" <?php language_attributes(); ?>>
	<![endif]-->
	<!--[if IE 8]>
	<html class="ie ie8 lte9 lte8" <?php language_attributes(); ?>>
	<![endif]-->
	<!--[if IE 9]>
	<html class="ie ie9" <?php language_attributes(); ?>>
	<![endif]-->
	<!--[if gt IE 9]>
	<html <?php language_attributes(); ?>> <![endif]-->
	<!--[if !IE]><!-->
<html <?php language_attributes(); ?>>
	<!--<![endif]-->
	<head>
		<meta charset="<?php bloginfo( 'charset' ); ?>"/>
		<meta name="viewport" content="width=device-width"/>

		<title><?php wp_title( '' ); ?></title>

		<link rel="profile" href="http://gmpg.org/xfn/11"/>
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>"/>

		<!-- IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="<?php echo get_template_directory_uri(); ?>/inc/js/html5.js" type="text/javascript"></script>
		<![endif]-->

		<?php wp_head(); ?>

	</head>

<body <?php body_class(); ?>>

<div id="top_header" class="container-full-width">
	<div class="container">
		<div id="wrapper" class="container-fluid">
			<div class="row-fluid">
				<div class="span6">
					<div class="top-head-description">
						<?php echo get_bloginfo( 'description' ); ?>
					</div>
					<!-- description -->
				</div>
				<!-- span 6 -->
				<!-- span 6 -->
				<div class="top-head-social span6">
					<?php cyberchimps_header_social_icons(); ?>
				</div>
				<!-- top head social -->
			</div>
			<!-- row fluid -->
		</div>
		<!-- wrapper -->
	</div>
	<!-- container -->
</div>
<!-- top header -->

<div id="main_header" class="container-full-width">
	<div class="container">
	
		<div id="wrapper" class="container-fluid">
			<div class="row-fluid">


<?php if (function_exists('pixopoint_menu')) {pixopoint_menu();} ?>

				<div class="span12">

					<?php do_action( 'cyberchimps_before_navigation' ); ?>

					<nav id="navigation" role="navigation">
						<div class="main-navigation navbar">
							<div class="navbar-inner">
								<div class="container">
									<?php /* hide collapsing menu if not responsive */
									if (cyberchimps_get_option( 'responsive_design', 'checked' )): ?>
									<div class="nav-collapse collapse">
										<?php endif; ?>


<!-- dropdown -->
        <style type="text/css">
            div#navbar-dropdown {
                color: red;
                position: absolute;
                z-index: 1000;
                margin-left: 13%;
                margin-right: 13%;
            }
            div#navbar-dropdown > div.container {
                background: #fff;
                border: 1px solid #000;
            }
            div.navbar-dropdown-container {
                color: red;
                position: absolute;
                z-index: 1000;
                background: #fff;
                border: 1px solid #000;
                width: 930px !important;
                left: -172px;
                top: 40px;
                height: 250px;
            }
        </style>

        <script type="text/javascript">
                    window.onload = function() {
                    document.getElementById('menu-item-119').onmouseover = function() {
                    document.getElementById('navbar-dropdown-homepage').style.display = 'block';
                    }
                    document.getElementById('menu-item-119').onmouseout = function() {
                    document.getElementById('navbar-dropdown-homepage').style.display = 'none';
                    }
                    document.getElementById('menu-item-75').onmouseover = function() {
                    document.getElementById('navbar-dropdown-news').style.display = 'block';
                    }
                    document.getElementById('menu-item-75').onmouseout = function() {
                    document.getElementById('navbar-dropdown-news').style.display = 'none';
                    }
                    document.getElementById('menu-item-71').onmouseover = function() {
                    document.getElementById('navbar-dropdown-speculations').style.display = 'block';
                    }
                    document.getElementById('menu-item-71').onmouseout = function() {
                    document.getElementById('navbar-dropdown-speculations').style.display = 'none';
                    }
                    document.getElementById('menu-item-67').onmouseover = function() {
                    document.getElementById('navbar-dropdown-outthepitch').style.display = 'block';
                    }
                    document.getElementById('menu-item-67').onmouseout = function() {
                    document.getElementById('navbar-dropdown-outthepitch').style.display = 'none';
                    }
                    }
        </script>

<?php
$query_str = $_SERVER['QUERY_STRING'];
$query = array();
parse_str($query_str, $query);
$page_id = "";
if (isset($query['page_id'])) {
    $page_id = $query['page_id'];
}
?>

                                                <div class="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f-container">
                                                    <ul id="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f" class="nav">
                                                        <li id="menu-item-119" class="menu-item menu-item-type-post_type menu-item-object-page page_item page-item-117
<?php if($page_id == "") echo " current_page_item active "; ?> menu-item-119">
                                                            <a href="http://62.44.109.7/projects/forumfootball/">Начало</a>
                                                        </li>

                                                        <li id="menu-item-75" class="menu-item 
<?php if($page_id == "36") echo " current_page_item active "; ?>
menu-item-type-post_type menu-item-object-page menu-item-75">
                                                            <a href="http://62.44.109.7/projects/forumfootball/?page_id=36">Новини</a>
                                                            <div id="navbar-dropdown-news" class="container navbar-dropdown-container" style="display: none;">
                                                                <div class="nav-collapse collapse">
                                                                    <div class="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f-container">
                                                                        <div class="box span8 al"
                                                                             style="border: 1px solid #888; height: 250px;">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480624.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>Христо Стоичков</h5>
<p>Нападателят Марин Петров..
</p>
                                                                                </div>
                                                                            </div>
                                                                            <div class="span11 h80" style="padding-left: 10px; margin-left: 0px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480585.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>футболисти в Левски</h5>
<p>Левски Владислав Мисяк,
</p>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="box span4 al">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <h5>Най-популярни</h5>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Premier League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>UEFA Champions League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Europa League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>World Cup</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Barcelona</p>
                                                                                    </a>
                                                                                </div>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>David Beckham</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Manchester United</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Liverpool</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Arsenal</p>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>       
                                                            </div>
                                                            <!-- news -->
                                                        </li>

                                                        <li id="menu-item-71" class="menu-item
<?php if($page_id == "38") echo " current_page_item active "; ?>
menu-item-type-post_type menu-item-object-page menu-item-71">
                                                            <a href="http://62.44.109.7/projects/forumfootball/?page_id=38">Трансферни спекулации</a>
                                                            <div id="navbar-dropdown-speculations" class="container navbar-dropdown-container" style="display: none;">
                                                                <div class="nav-collapse collapse">
                                                                    <div class="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f-container">
                                                                        <div class="box span8 al"
                                                                             style="border: 1px solid #888; height: 250px;">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480533.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>Христо Стоичков</h5>
<p>Нападателят Марин Петров..
</p>
                                                                                </div>
                                                                            </div>
                                                                            <div class="span11 h80" style="padding-left: 10px; margin-left: 0px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480585.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>футболисти в Левски</h5>
<p>Левски Владислав Мисяк,
</p>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="box span4 al">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <h5>Най-популярни</h5>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Premier League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>UEFA Champions League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Europa League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>World Cup</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Barcelona</p>
                                                                                    </a>
                                                                                </div>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>David Beckham</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Manchester United</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Liverpool</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Arsenal</p>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>       
                                                            </div>
                                                            <!-- speculations -->
                                                        </li>
<?php /*
                                                        <li id="menu-item-69" class="menu-item
<?php if($page_id == "40") echo " current_page_item active "; ?>
menu-item-type-post_type menu-item-object-page menu-item-69">
                                                            <a href="http://62.44.109.7/projects/forumfootball/?page_id=40">Първенства</a>
                                                            <div id="navbar-dropdown-championships" class="container navbar-dropdown-container" style="display: none;">
                                                                <div class="nav-collapse collapse">
                                                                    <div class="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f-container">
                                                                        <div class="box span8 al"
                                                                             style="border: 1px solid #888; height: 250px;">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480613.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>Христо Стоичков</h5>
<p>Нападателят Марин Петров..
</p>
                                                                                </div>
                                                                            </div>
                                                                            <div class="span11 h80" style="padding-left: 10px; margin-left: 0px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480585.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>футболисти в Левски</h5>
<p>Левски Владислав Мисяк,
</p>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="box span4 al">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <h5>Най-популярни</h5>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Premier League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>UEFA Champions League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Europa League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>World Cup</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Barcelona</p>
                                                                                    </a>
                                                                                </div>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>David Beckham</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Manchester United</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Liverpool</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Arsenal</p>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>       
                                                            </div>
                                                            <!-- championships -->
                                                        </li>

                                                        <li id="menu-item-70" class="menu-item 
<?php if($page_id == "42") echo " current_page_item active "; ?>
menu-item-type-post_type menu-item-object-page menu-item-70">
                                                            <a href="http://62.44.109.7/projects/forumfootball/?page_id=42">Статии</a>
                                                            <div id="navbar-dropdown-articles" class="container navbar-dropdown-container" style="display: none;">
                                                                <div class="nav-collapse collapse">
                                                                    <div class="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f-container">
                                                                        <div class="box span8 al"
                                                                             style="border: 1px solid #888; height: 250px;">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480611.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>Христо Стоичков</h5>
<p>Нападателят Марин Петров..
</p>
                                                                                </div>
                                                                            </div>
                                                                            <div class="span11 h80" style="padding-left: 10px; margin-left: 0px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480585.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>футболисти в Левски</h5>
<p>Левски Владислав Мисяк,
</p>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="box span4 al">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <h5>Най-популярни</h5>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Premier League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>UEFA Champions League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Europa League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>World Cup</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Barcelona</p>
                                                                                    </a>
                                                                                </div>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>David Beckham</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Manchester United</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Liverpool</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Arsenal</p>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>       
                                                            </div>
                                                            <!-- articles -->
                                                        </li>
*/ ?>
                                                        <li id="menu-item-67" class="menu-item
<?php if($page_id == "44") echo " current_page_item active "; ?>
menu-item-type-post_type menu-item-object-page menu-item-67">
                                                            <a href="http://62.44.109.7/projects/forumfootball/?page_id=44">Извън терена</a>
								<div id="navbar-dropdown-outthepitch" class="container navbar-dropdown-container" style="display: none;">
                                                                <div class="nav-collapse collapse">
                                                                    <div class="menu-%d0%bd%d0%b0%d0%b2%d0%b8%d0%b3%d0%b0%d1%86%d0%b8%d1%8f-container">
                                                                        <div class="box span8 al"
                                                                             style="border: 1px solid #888; height: 250px;">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480611.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>Христо Стоичков</h5>
<p>Нападателят Марин Петров..
</p>
                                                                                </div>
                                                                            </div>
                                                                            <div class="span11 h80" style="padding-left: 10px; margin-left: 0px;">
                                                                                <div class="span3">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <br>
                                                                                        <img class="box-image" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/04/00480585.jpg">				                                                                                                            </a>
                                                                                </div>
                                                                                <div class="span8">
                                                                                    <br/>
                                                                                    <h5>футболисти в Левски</h5>
<p>Левски Владислав Мисяк,
</p>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="box span4 al">
                                                                            <div class="span11 h80" style="padding-left: 10px;">
                                                                                <h5>Най-популярни</h5>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Premier League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>UEFA Champions League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Europa League</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>World Cup</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Barcelona</p>
                                                                                    </a>
                                                                                </div>
                                                                                <div class="span5">
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>David Beckham</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Manchester United</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Liverpool</p>
                                                                                    </a>
                                                                                    <a href="http://www.toto.bg/" class="box-link">
                                                                                        <p>Arsenal</p>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>       
                                                            </div>
                                                            <!-- outthepitch -->                                                        
							</li>
                                                    </ul>
                                                </div>
                                                



<?php /*
	
/////////////////////////////////// TTT

									<?php wp_nav_menu( array( 'theme_location' => 'primary', 'menu_class' => 'nav', 'walker' => new cyberchimps_walker(), 'fallback_cb' => 'cyberchimps_fallback_menu' ) ); ?>

*/ ?>
	

										<?php /* hide collapsing menu if not responsive */
										if (cyberchimps_get_option( 'responsive_design', 'checked' )): ?>
									</div>
								<!-- collapse -->

								<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
									<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</a>
								<?php endif; ?>
								</div>
								<!-- container -->
							</div>
							<!-- .navbar-inner .row-fluid -->
						</div>
						<!-- main-navigation navbar -->
					</nav>
					<!-- #navigation -->

					<?php do_action( 'cyberchimps_after_navigation' ); ?>

				</div>
				<!-- nav span 6 -->
			</div>
			<!-- row-fluid -->
		</div>
		<!-- wrapper -->
	</div>
	<!-- container -->


</div>
<!-- main header -->

<!-- grand banner -->
<div id="grand_banner_header" class="container-full-width">
	<div class="container">
		<div class="container-fluid" style="text-align: center;">
			<img style="width: 728px; height:90px;" src="http://62.44.109.7/projects/forumfootball/wp-content/uploads/2014/06/Fotor062964827.png" />
		</div>
	</div>
</div>
<!-- grand banner -->

<?php do_action( 'cyberchimps_before_wrapper' ); ?>